fix: Set secure cookie options to stop Safari from discarding cookies
actcoding/intranet pull request #11
Opened 2024-10-05 15:24 UTC by cwerl

2024-10-07 07:01 UTC, axelrindle requested changes

2024-10-07 07:01 UTC, axelrindle commented on frontend/src/lib/actions/auth.ts
> +            secure: process.env.NODE_ENV === 'production',
Kannst du hierfür noch einen Helper bauen? Sowas wie `isProduction()`

2024-10-07 07:02 UTC, axelrindle commented
Kannst du auch noch kurz beschreiben, was genau der Fix für Safari ist?

2024-10-07 07:53 UTC, cwerl commented
> Kannst du auch noch kurz beschreiben, was genau der Fix für Safari ist?

Habs in der Beschreibung ergänzt.

2024-10-07 11:19 UTC, axelrindle commented on frontend/src/lib/actions/auth.ts
> +            // TODO: Evaluate most appropriate cookie settings
Ich denke der default `SameSite=lax` ist in Ordnung, daher das TODO gerne wieder raus.

Du kannst ansonsten mal testen, wie es sich mit `SameSite=strict` verhält.

2024-10-13 11:15 UTC, cwerl commented on frontend/src/lib/actions/auth.ts
> +            // TODO: Evaluate most appropriate cookie settings
stricht funktioniert auch

2024-10-13 18:51 UTC, axelrindle approved these changes

2024-10-13 18:51 UTC, merged