feat: link events and news
actcoding/intranet pull request #28
Opened 2024-12-25 21:58 UTC by cwerl

2024-12-27 13:23 UTC, cwerl commented
@axelrindle Den Badge direkt bei den NewsPreviewCards konnte ich nicht implementieren, da linkedEvents immer undefined ist, wenn man die News List aufruft

2024-12-27 13:26 UTC, axelrindle commented
@cwerl Schau ich mir morgen an

2024-12-27 22:54 UTC, axelrindle requested changes
![Bildschirmfoto 2024-12-27 um 23 52 57](https://github.com/user-attachments/assets/3583d9c4-e1f2-4010-bd2d-3073b2d95c53)

Wenn ich auf den Link klicke, passiert nichts.
Verknüpfung aufheben geht.

2024-12-28 10:55 UTC, cwerl commented
> ![Bildschirmfoto 2024-12-27 um 23 52 57](https://private-user-images.githubusercontent.com/7105632/399019202-3583d9c4-e1f2-4010-bd2d-3073b2d95c53.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUzODM1OTksIm5iZiI6MTczNTM4MzI5OSwicGF0aCI6Ii83MTA1NjMyLzM5OTAxOTIwMi0zNTgzZDljNC1lMWYyLTQwMTAtYmQyZC0zMDczYjJkOTVjNTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjhUMTA1NDU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGVhNmZiZjkxNGE0MjI3MzQ2NGZhZDJlNmJjNmVkNjBhMTk4MWI3Y2NlN2ZjNDhkYWRmZmM0NDVhYTE4MTZjMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Y-K5sWG8JOuqUj2hBoA0AKmFJ_bsZQ2iWIsG4PoEKPQ)
> 
> Wenn ich auf den Link klicke, passiert nichts. Verknüpfung aufheben geht.

fixed

2024-12-28 11:45 UTC, axelrindle approved these changes

2024-12-28 11:45 UTC, merged