ILENE-15: Newsfeed - Datenmodell
actcoding/intranet pull request #4
Opened 2024-06-28 17:15 UTC by axelrindle

Implements the `News` entity.

2024-07-03 15:55 UTC, cwerl commented
Sieht soweit gut aus. Ich würde nur nochmal den Formatter über die Dateien laufen lassen und einmal organize Imports machen, hier und da sind noch ein paar unused Imports (was macht das Lucide Icon in der actions.ts? xD). Dann sollte es passen.

2024-07-03 15:56 UTC, cwerl requested changes
Sieht soweit gut aus. Ich würde nur nochmal den Formatter über die Dateien laufen lassen und einmal organize Imports machen, hier und da sind noch ein paar unused Imports (was macht das Lucide Icon in der actions.ts? xD). Dann sollte es passen.

2024-07-03 18:18 UTC, axelrindle commented
Ich bastel noch an der Validierung gerade und räume ein wenig auf.

2024-07-06 13:38 UTC, cwerl requested changes

2024-07-06 13:38 UTC, cwerl commented on frontend/src/lib/components/auth/reset-form/PasswordResetForm.tsx
> +        if (res === undefined) {
In dem Fall würde man ein Success bekommen wenn z.B. mal das Backend nicht erreichbar ist, ich würde eher folgende Fälle abfragen:

- res.ok => success
- res.errors => laravel errors
- catch-all mit generischen Fehlern

2024-07-06 13:38 UTC, cwerl commented on frontend/src/lib/utils.ts
> +export function setLaravelErrors<T extends FieldValues = FieldValues>(
```suggestion
export function setLaravelFormErrors<T extends FieldValues = FieldValues>(
```

2024-07-06 13:38 UTC, cwerl commented on frontend/src/types.ts
> +export type ToZod<T> = {
nice stuff

2024-07-06 13:38 UTC, cwerl commented on frontend/src/app/actions.ts
> +        return {
Warum geben wir nur einen Teil der Response zurück? Und warum benennen wir "status" in "code" um? Bei API Requests würde ich immer ein "status" Attribut erwarten.

2024-07-06 19:29 UTC, cwerl requested changes

2024-07-06 19:29 UTC, cwerl commented on frontend/src/app/actions.ts
> +            ...data,
hier könnte man sich jetzt bisschen code sparen und direkt data zurückgeben oder?

2024-07-06 19:29 UTC, cwerl commented on frontend/src/app/actions.ts
> +            ...data,
s.o.

2024-07-06 19:29 UTC, cwerl commented on frontend/src/lib/components/auth/login-form/LoginForm.tsx
> +            if (res !== undefined) {
Hmm ich finde if(res) irgendwie lesbarer weil ich das im Kopf als "if there is a result" lese und man bei Negationen immer verkehrt herum denken muss. Aber ist eher persönliche Präferenz, muss jetzt nicht unbedingt geändert werden.

Aber nices Error handling jetzt

2024-07-06 19:29 UTC, cwerl commented on frontend/src/types.ts
> +export type ApiResponse = {
Gibts nicht schon einen Type dafür? Oder ist das maßgeschneidert für Laravel REST?

2024-07-06 19:31 UTC, axelrindle commented on frontend/src/app/actions.ts
> +            ...data,
Ne weil der Status aus der Response kommt (HTTP), `data´ ist der body.

2024-07-06 19:32 UTC, axelrindle commented on frontend/src/types.ts
> +export type ApiResponse = {
Welchen Type meinst

2024-07-06 19:36 UTC, axelrindle commented on frontend/src/types.ts
> +export type ApiResponse = {
Aber ja ist "maßgeschneidert" :D

2024-07-06 20:18 UTC, cwerl commented on frontend/src/types.ts
> +export type ApiResponse = {
Diesen Standard Response Type den man von fetch zuückbekommt. Aber wenn der nicht ausreicht können wir den natürlich ersetzen/extenden.

2024-07-06 20:21 UTC, axelrindle commented on frontend/src/types.ts
> +export type ApiResponse = {
Wie heißt der bzw. wie sieht der aus

2024-07-06 20:24 UTC, cwerl commented on frontend/src/types.ts
> +export type ApiResponse = {
https://developer.mozilla.org/en-US/docs/Web/API/Response bzw https://nextjs.org/docs/app/api-reference/functions/next-response

2024-07-06 20:36 UTC, axelrindle commented on frontend/src/types.ts
> +export type ApiResponse = {
Achso, also der Typ ist dafür da dass wir typesafe die Daten rauslesen können

2024-07-06 20:53 UTC, cwerl approved these changes

2024-07-06 21:03 UTC, merged